name: Coverage Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - otp: '24.2'
            elixir: '1.12.3'
          - otp: '25.3.2.10'
            elixir: '1.14.4'
          - otp: '26.2.5'
            elixir: '1.15.7'
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - uses: erlef/setup-beam@main
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix coveralls.github --exclude real_cover
